---
kind: pipeline
type: exec
name: "Ubuntu 22.04: g++11 + debug + sanitize addr+ub + tests"

platform:
  arch: amd64
  os: linux

steps:
  - name: install dependencies
    commands:
      - sudo apt install build-essential cmake
  - name: configure
    commands:
      - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DTESTING=1 -DSANITAIZERS=1
  - name: build
    commands:
      - cmake --build build -j$(nproc)
  - name: testing
    commands:
      - ./build/tests/bcrypt_tests
