---
kind: pipeline
name: "Ubuntu 22.04: g++11 + debug + sanitize addr+ub + tests"

platform:
  arch: amd64
  os: linux

steps:
  - name: "Ubuntu 22.04: g++11 + debug + sanitize addr+ub + tests"
    image: ubuntu
    commands:
      - apt update -y
      - apt install -y cmake build-essential
      - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DTESTING=1 -DSANITIZERS=1
      - cmake --build build -j$(nproc)
      - ./build/tests/bcrypt_tests

---
kind: pipeline
type: exec
name: "Ubuntu 22.04: clang++-14 + debug + sanitize addr+ub + tests"

platform:
  arch: amd64
  os: linux

steps:
  - name: configure
    commands:
      - cmake -B build -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_C_COMPILER=clang-14 -DCMAKE_BUILD_TYPE=Debug -DTESTING=1 -DSANITIZERS=1
  - name: build
    commands:
      - cmake --build build -j$(nproc)
  - name: testing
    commands:
      - ./build/tests/bcrypt_tests

---
kind: pipeline
type: exec
name: "Ubuntu 22.04: clang++-14 + release"

platform:
  arch: amd64
  os: linux

steps:
  - name: configure
    commands:
      - cmake -B build -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_C_COMPILER=clang-14 -DCMAKE_BUILD_TYPE=Release
  - name: build
    commands:
      - cmake --build build -j$(nproc)
