---
kind: pipeline
name: "Ubuntu 22.04: g++11 + debug + sanitize addr+ub + tests"

platform:
  arch: amd64
  os: linux

steps:
  - name: "Ubuntu 22.04: g++11 + debug + sanitize addr+ub + tests"
    image: ubuntu:22.04
    commands:
      - apt update -y
      - apt install -y cmake build-essential
      - cmake -B build -DCMAKE_BUILD_TYPE=Debug -DTESTING=1 -DSANITIZERS=1
      - cmake --build build -j$(nproc)
      - ./build/tests/bcrypt_tests

---
kind: pipeline
name: "Ubuntu 22.04: clang++-14 + debug + sanitize addr+ub + tests"

platform:
  arch: amd64
  os: linux

steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - apt update -y
      - apt install cmake build-essential clang -y
      - cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -DTESTING=1 -DSANITIZERS=1
        - cmake --build build -j$(nproc)
        - ./build/tests/bcrypt_tests

---
kind: pipeline
name: "Ubuntu 22.04: clang++-14 + release"

platform:
  arch: amd64
  os: linux

steps:
  - name: build
    image: ubuntu:22.04
    commands:
      - apt update -y
      - apt install cmake build-essential clang -y
      - cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
      - cmake --build build -j$(nproc)
